name: TwitchRewardListener
version: 1.0
main: com.davidemodolo.twitchreward.TwitchRewardListener
api-version: 1.20
authors: [Davide Modolo]
commands:
  twitchreward:
    description: Main command for TwitchRewardListener
    usage: /twitchreward reload
    permission: twitchreward.admin
permissions:
  twitchreward.admin:
    description: Allows reloading the plugin config
    default: op