name: Build and Release Plugin

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TwitchRewardListener-Jar
        path: target/TwitchRewardListener-*.jar

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: target/TwitchRewardListener-*.jar
        generate_release_notes: true
